const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    /* [_BASE] =   { ENCODER_CCW_CW(KC_MS_WH_UP, KC_MS_WH_DOWN) }, */
    [_BASE] =   { ENCODER_CCW_CW(KC_DOWN, KC_UP) },
    [_ALT] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_RAISE] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_SHIFTLOCK] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },


    [_LOWER] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },



    [_ROFI] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_EMACS] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_SA] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_MOUSE] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_SUPER] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_EDITING] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_WINMOVE] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_ALL_MODS] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_SYSTEM] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_WINDOWS] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_MACROS] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_ADHOC_SET_HOTKEY] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_HYPER] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },


    [_LAYER_LOCK] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_CODE] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_EMACS_SELECT] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },

    [_FILES] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_WEB] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_MOTION] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) },
    [_LEADER1] = { ENCODER_CCW_CW(KC_PGDOWN, KC_PGUP) }
};
