DEFERRED_EXEC_ENABLE = yes

# SRC += muse.c
# AUDIO_ENABLE = yes
# AUTOCORRECT_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
# AUTO_SHIFT_MODIFIERS = yes
# CAPS_WORD_ENABLE = yes

# COMMAND_ENABLE = yes
# CONSOLE_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# # KEY_OVERRIDE_ENABLE =no
# LEADER_ENABLE = yes
# MIDI_ENABLE = yes
# NKRO_ENABLE = yes
# REPEAT_KEY_ENABLE = yes
# RGBLIGHT_ANIMATIONS = yes
# RGBLIGHT_ENABLE = yes
# RGB_ANIMATIONS = yes
# # TAP_DANCE_ENABLE = yes
# WEBUSB_ENABLE = yes
