SRC += muse.c

# BACKLIGHT_ENABLE = yes
# RGBLIGHT_ANIMATIONS = yes
# RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
AUTO_SHIFT_MODIFIERS = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = yes
MIDI_ENABLE = yes
NKRO_ENABLE = yes
ORYX_ENABLE = yes
RGB_ANIMATIONS = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
WEBUSB_ENABLE = yes
# RGB_MATRIX_CUSTOM_KB = yes


# SRC = matrix.c
