# SRC += muse.c
EXTRAFLAGS += -flto
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
# AUTO_SHIFT_ENABLE = yes

# TAP_DANCE_ENABLE = yes
TERMINAL_ENABLE = no

ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
