SRC += muse.c

REPEAT_KEY_ENABLE = yes
# SRC += ../../../common/layer_lock.c
# VELOCIKEY_ENABLE = yes

AUDIO_ENABLE = yes
AUTOCORRECT_ENABLE = yes
AUTO_SHIFT_ENABLE = no
# AUTO_SHIFT_MODIFIERS = yes
# CAPS_WORD_ENABLE = yes
# KEY_LOCK_ENABLE = yes

COMBO_ENABLE = yes
# COMMAND_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
# ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
REPEAT_KEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes
MIDI_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ANIMATIONS = yes
RGBLIGHT_ENABLE = yes
RGB_ANIMATIONS = yes
TAP_DANCE_ENABLE = yes
WEBUSB_ENABLE = yes

# UNICODE_COMMON = yes
# UNICODEMAP_ENABLE = yes
# UCIS_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
